version: '3.8'
services:
  laravelMysql:
    image: mysql
    container_name: simple_pay_mysql
    restart: always
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 33061:3306
volumes:
  mysql_data:
